# Generated by Django 4.1 on 2022-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Pca'), (1, 'Simca'), (2, 'Plsda'), (3, 'Knn'), (4, 'Svm')], default=1)),
                ('modelfile', models.FileField(upload_to='datamodelfiles')),
            ],
            options={
                'verbose_name': 'Data Model',
                'verbose_name_plural': 'Data Models',
            },
        ),
    ]
