# Generated by Django 4.1 on 2022-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='modelfile',
            field=models.FileField(upload_to='models'),
        ),
    ]
