# Generated by Django 4.1 on 2022-09-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodelapp', '0002_alter_datamodel_modelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='name',
            new_name='modelname',
        ),
    ]
