# Generated by Django 4.1 on 2022-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRun',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('samplefile', models.FileField(upload_to='samples')),
                ('model', models.IntegerField(choices=[(0, 'Pca'), (1, 'Simca'), (2, 'Plsda'), (3, 'Knn'), (4, 'Svm')])),
                ('result', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Sample Run',
                'verbose_name_plural': 'Sample Runs',
            },
        ),
    ]
