# Generated by Django 4.1 on 2022-09-10 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamodelapp', '0003_rename_name_datamodel_modelname'),
        ('cdaapp', '0002_alter_samplerun_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplerun',
            name='model',
        ),
        migrations.AddField(
            model_name='samplerun',
            name='modelname',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.RESTRICT, to='datamodelapp.datamodel'),
            preserve_default=False,
        ),
    ]
