# Generated by Django 4.1 on 2022-09-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdaapp', '0003_remove_samplerun_model_samplerun_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerun',
            name='time',
            field=models.PositiveBigIntegerField(default=1662808744235738000, primary_key=True, serialize=False),
        ),
    ]
