# Generated by Django 4.1 on 2022-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdaapp', '0004_alter_samplerun_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerun',
            name='time',
            field=models.PositiveBigIntegerField(default=1662808938440718200, editable=False, primary_key=True, serialize=False),
        ),
    ]
