# Generated by Django 4.1 on 2022-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdaapp', '0007_alter_samplerun_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerun',
            name='time',
            field=models.TimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
