# Generated by Django 4.1 on 2022-09-10 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdaapp', '0010_alter_samplerun_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerun',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, primary_key=True, serialize=False),
        ),
    ]
