# Generated by Django 4.1 on 2022-09-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodelapp', '0003_rename_name_datamodel_modelname'),
        ('cdaapp', '0011_alter_samplerun_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('samplefile', models.FileField(upload_to='samples')),
                ('result', models.TextField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('modelname', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datamodelapp.datamodel')),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
            },
        ),
        migrations.DeleteModel(
            name='SampleRun',
        ),
    ]
